language: ruby
rvm:
- 2.2.5
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: SpYtkLf1p1kEVr66lKnM1tL6/9RN7d5mzUtDZ+V+Hgt+yD7PY9me8vr2B6cPNzTOCSRqD4u187N8bWPAy3wHooHZesKQobUluQEBPzhsckyXz+YRhr4a0ETGfaNnZGHplt+rYgjHahE/VwHpPTsErmp9eDiI1TLvgeiHwZLFwI+HwVkI4EBw81AI+CBDe9tK/WIOXubUqECAsO0Gq1e/cYeZwbUjhT3kXygperT9XnT2dmOy9RIrOnlyqcVbsRez6Ejipn3l8wJruNcIFAsh2dszCPfBxbCMFXqxgZBKE67ovGo7nX7oX4kCeLUMoz9ME3v1DJ+iw+RahkcdPPeImZc4FXrxXjyFYYjRg3ync/zkiH11gkajrwlZQAQDUAIXf913BvkDBfEcARLmGEzY+nDCfauIOHmNIKlNDDonI2x+5wzAoucGgI3WUefIgkb5jFQvwMwxyrIdobPjyIk8lADqpsjDEGJmt92HVLnpwN7RPyxiDk4rPAEAnnJ9elL11oxk/SFY6fK+XxukB330VSJur8dHS9WbJVpaln4Be5O/sRYPUEsaZnx2+ntb3og9HXJgMs69XUjAwgpDRCfSpJpkdIiSpIryBKWIHw9MCC7pQiPUsUt4GJ488xlgwZqe1fbvsq8vmFxa+QNM8DSFMjJ523hh0lPns30Y1omObus=
