= The Secure Developer Community Reporting Guidelines
:page-title: The Secure Developer Community Reporting Guidelines
:page-description: The Secure Developer
:icons: font
:showtitle:

{nbsp} +

If you believe someone is violating the code of conduct we ask that you report it to the Secure Developer Community organizers by emailing [TBD]. Reports will be received by [name, name]. [Alternative means of contact in case you're reporting one of those people]

**All reports will be kept confidential.** In some cases we may determine that a public statement will need to be made. If that's the case, the identities of all victims and reporters will remain confidential unless those individuals instruct us otherwise.

If you believe anyone is in physical danger, please notify appropriate emergency services first. If you are unsure what service or agency is appropriate to contact, include this in your report and we will attempt to notify them.

In your report please include:

* Your contact info for follow-up contact.
* Names (legal, nicknames, or pseudonyms) of any individuals involved.
  * If there were other witnesses besides you, please try to include them as well.
* When and where the incident occurred. Please be as specific as possible.
* Your account of what occurred.
  * If there is a publicly available record (e.g. a mailing list archive or a public IRC logger) please include a link.
* Any extra context you believe existed for the incident.
* If you believe this incident is ongoing.
* Any other information you believe we should have.

== What happens after you file a report?

You will receive an email from the The Secure Developer's Code of Conduct response team acknowledging receipt as soon as possible[, but within 24 hours.]

The working group will meet as soon as possible to review the incident report and determine:

* What happened.
* Whether this event constitutes a code of conduct violation.
* What kind of response is appropriate.

If this is determined to be an ongoing incident or a threat to physical safety, the team's immediate priority will be to protect everyone involved. This means we may delay an "official" response until we believe that the situation has ended and that everyone is physically safe.

Once the team has a complete account of the events they will make a decision as to how to respond. Responses may include:

* Nothing (if we determine no Code of Conduct violation occurred).
* A private reprimand from the Code of Conduct response team to the individual(s) involved.
* A public reprimand.
* A permanent or temporary ban from some or all Secure Developer spaces (events, meetings, mailing lists, IRC, etc.)
* A request to engage in mediation and/or an accountability plan.

We'll respond within one week to the person who filed the report with either a resolution or an explanation of why the situation is not yet resolved.

Once we've determined our final action, we'll contact the original reporter to let them know what action (if any) we'll be taking. We'll take into account feedback from the reporter on the appropriateness of our response, but our response will be determined by what will be best for community safety.

== Appealing the response

Only permanent resolutions (such as bans) may be appealed. To appeal a decision of the working group, contact us at [contact] with your appeal and we will review the case.

_Reporting Guidelines derived from those of the https://www.djangoproject.com/conduct/reporting/[Django Software Foundation]._
